### ISSUE TITLE
Assignment 1 ready for review

### ISSUE THREAD

**Issue by whytnestevens** [SES-5215-F2020/whytnestevens-quant#1]
My .Rmd and html files are ready for review grading. I look forward to your feedback and suggestions.

**Comment by saratepfer** [comment]
Thank you, Whytne! I'm so sorry the original feedback I gave didn't seem to go through. Your assignment 1 looks great. Nice job using the PUMAs to narrow down your dataset. 

Just one comment: I would also state explicitly that you are looking at currently working people in Dallas County, as you filter for income > 0.
