### ISSUE TITLE
Assignment 1 NOW ready for grading

### ISSUE THREAD

**Issue by whytnestevens** [SES-5215-F2020/whytnestevens-quant#3]
I have now edited my initial Assignment 1 based on class and out of class help from classmates. Looking forward to feedback and suggestions, particularly tips/best practices on how to make a more compelling dataset

**Comment by saratepfer** [comment]
Thank you, Whytne! Nice work on this. Your level of analysis and number of observations are clearly stated. I think you could tweak your statement of sample population slightly, by adding that you are including only those people whose work hours per week is greater than zero.

**Comments on Content**
You are currently working with a lot of variables! It's possible (and totally fine) that you reduce the number of variables in your dataset as the semester progresses.

**Comments on Code**
Line 43: You shouldn't need this line, as you are working with person-level variables.
Your approach for converting the SOCP variable to numeric and filtering for values greater than zero works. Another approach would be to keep it as it is and filter out the N/A term using filter(SOCP != "insert N/A term here")
